# Generated by Django 4.1.3 on 2023-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carid', models.CharField(db_column='CarID', max_length=255, primary_key=True, serialize=False)),
                ('carstate', models.IntegerField(blank=True, db_column='CarState', null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('passengerid', models.CharField(db_column='PassengerID', max_length=255)),
                ('driverid', models.CharField(db_column='DriverID', max_length=255)),
                ('orderid', models.CharField(db_column='OrderID', max_length=255, primary_key=True, serialize=False)),
                ('reservationtime', models.CharField(blank=True, db_column='ReservationTime', max_length=255, null=True)),
                ('startingpoint', models.CharField(blank=True, db_column='StartingPoint', max_length=255, null=True)),
                ('startinglongitude', models.CharField(blank=True, db_column='StartingLongitude', max_length=255, null=True)),
                ('startinglatitude', models.CharField(db_column='StartingLatitude', max_length=255)),
                ('endingpoint', models.CharField(blank=True, db_column='EndingPoint', max_length=255, null=True)),
                ('endinglongitude', models.CharField(blank=True, db_column='EndingLongitude', max_length=255, null=True)),
                ('endinglatitude', models.CharField(blank=True, db_column='EndingLatitude', max_length=255, null=True)),
                ('type', models.PositiveIntegerField(blank=True, db_column='Type', null=True)),
                ('sideid', models.CharField(blank=True, db_column='SideID', max_length=255, null=True)),
                ('dispatchtime', models.CharField(blank=True, db_column='DispatchTime', max_length=255, null=True)),
                ('boardingtime', models.CharField(blank=True, db_column='BoardingTime', max_length=255, null=True)),
                ('departuretime', models.CharField(blank=True, db_column='DepartureTime', max_length=255, null=True)),
                ('driverstartinglongitude', models.CharField(blank=True, db_column='DriverStartingLongitude', max_length=255, null=True)),
                ('driverstartinglatitude', models.CharField(blank=True, db_column='DriverStartingLatitude', max_length=255, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataNew',
            fields=[
                ('passengerid', models.CharField(db_column='PassengerID', max_length=255)),
                ('driverid', models.CharField(db_column='DriverID', max_length=255)),
                ('orderid', models.CharField(db_column='OrderID', max_length=255, primary_key=True, serialize=False)),
                ('reservationtime', models.CharField(blank=True, db_column='ReservationTime', max_length=255, null=True)),
                ('startingpoint', models.CharField(blank=True, db_column='StartingPoint', max_length=255, null=True)),
                ('startinglongitude', models.CharField(blank=True, db_column='StartingLongitude', max_length=255, null=True)),
                ('startinglatitude', models.CharField(db_column='StartingLatitude', max_length=255)),
                ('endingpoint', models.CharField(blank=True, db_column='EndingPoint', max_length=255, null=True)),
                ('endinglongitude', models.CharField(blank=True, db_column='EndingLongitude', max_length=255, null=True)),
                ('endinglatitude', models.CharField(blank=True, db_column='EndingLatitude', max_length=255, null=True)),
                ('type', models.PositiveIntegerField(blank=True, db_column='Type', null=True)),
                ('sideid', models.CharField(blank=True, db_column='SideID', max_length=255, null=True)),
                ('driverstartinglongitude', models.CharField(blank=True, db_column='DriverStartingLongitude', max_length=255, null=True)),
                ('driverstartinglatitude', models.CharField(blank=True, db_column='DriverStartingLatitude', max_length=255, null=True)),
            ],
            options={
                'db_table': 'data_new',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverid', models.CharField(db_column='DriverID', max_length=255)),
                ('driverstate', models.IntegerField(blank=True, db_column='DriverState', null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverid', models.CharField(blank=True, db_column='DriverID', max_length=255, null=True)),
                ('carid', models.CharField(blank=True, db_column='CarID', max_length=255, null=True)),
                ('startingtime', models.CharField(blank=True, db_column='StartingTime', max_length=255, null=True)),
                ('endingtime', models.CharField(blank=True, db_column='EndingTime', max_length=255, null=True)),
            ],
            options={
                'db_table': 'driving',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(db_column='OrderID', max_length=255, primary_key=True, serialize=False)),
                ('dispatchtime', models.CharField(blank=True, db_column='DispatchTime', max_length=255, null=True)),
                ('boardingtime', models.CharField(blank=True, db_column='BoardingTime', max_length=255, null=True)),
                ('departuretime', models.CharField(blank=True, db_column='DepartureTime', max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerid', models.CharField(db_column='PassengerID', max_length=255, primary_key=True, serialize=False)),
                ('passengerstate', models.IntegerField(blank=True, db_column='PassengerState', null=True)),
            ],
            options={
                'db_table': 'passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.CharField(db_column='ReservationID', max_length=255, primary_key=True, serialize=False)),
                ('reservationtime', models.CharField(blank=True, db_column='ReservationTime', max_length=255, null=True)),
                ('startingpoint', models.CharField(blank=True, db_column='StartingPoint', max_length=255, null=True)),
                ('startinglatitude', models.CharField(blank=True, db_column='StartingLatitude', max_length=255, null=True)),
                ('startinglongitude', models.CharField(blank=True, db_column='StartingLongitude', max_length=255, null=True)),
                ('endingpoint', models.CharField(blank=True, db_column='EndingPoint', max_length=255, null=True)),
                ('endinglongitude', models.CharField(blank=True, db_column='EndingLongitude', max_length=255, null=True)),
                ('endinglatitude', models.CharField(blank=True, db_column='EndingLatitude', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Riding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerid', models.CharField(blank=True, db_column='PassengerID', max_length=255, null=True)),
                ('carid', models.CharField(blank=True, db_column='CarID', max_length=255, null=True)),
                ('orderid', models.CharField(blank=True, db_column='OrderID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'riding',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(db_column='UserID', max_length=255, primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('passengerid', models.CharField(db_column='PassengerID', max_length=255, primary_key=True, serialize=False)),
                ('reservationid', models.CharField(db_column='ReservationID', max_length=255)),
                ('astate', models.IntegerField(blank=True, db_column='AState', null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': True,
                'unique_together': {('passengerid', 'reservationid')},
            },
        ),
    ]
